"""add storage quota

Revision ID: 1eab3c8789c7
Revises: 2c3a0831165a
Create Date: 2026-07-27 13:04:19.713016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eab3c8789c7'
down_revision: Union[str, Sequence[str], None] = '2c3a0831165a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "users",
        sa.Column(
            "storage_quota",
            sa.BigInteger(),
            nullable=False,
            server_default=str(5 * 1024 * 1024 * 1024),  # 5 GB
        ),
    )

    op.add_column(
        "users",
        sa.Column(
            "storage_used",
            sa.BigInteger(),
            nullable=False,
            server_default="0",
        ),
    )

    # Remove the defaults after existing rows are populated
    op.alter_column(
        "users",
        "storage_quota",
        server_default=None,
    )

    op.alter_column(
        "users",
        "storage_used",
        server_default=None,
    )
# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('users', sa.Column('storage_quota', sa.BigInteger(), nullable=False))
#     op.add_column('users', sa.Column('storage_used', sa.BigInteger(), nullable=False))
#     # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'storage_used')
    op.drop_column('users', 'storage_quota')
    # ### end Alembic commands ###
