"""Initial migration

Revision ID: 28a57a907d27
Revises: 
Create Date: 2026-07-26 11:34:33.503823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28a57a907d27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('description', sa.String(), nullable=True))
    op.add_column(
        'folders',
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )

    op.add_column(
        'folders',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )

    op.alter_column('folders', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('folders', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('folders', 'updated_at')
    op.drop_column('folders', 'created_at')
    op.drop_column('folders', 'description')
    # ### end Alembic commands ###
