"""create files table

Revision ID: 8006b116573c
Revises: 28a57a907d27
Create Date: 2026-07-26 18:56:20.639023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8006b116573c'
down_revision: Union[str, Sequence[str], None] = '28a57a907d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('original_name', sa.String(), nullable=False))
    op.add_column('files', sa.Column('stored_name', sa.String(), nullable=False))
    op.add_column('files', sa.Column('file_path', sa.String(), nullable=False))
    op.add_column('files', sa.Column('mime_type', sa.String(), nullable=False))
    op.add_column('files', sa.Column('file_size', sa.BigInteger(), nullable=False))
    op.add_column('files', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('files', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('files', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('files', 'folder_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_unique_constraint(None, 'files', ['stored_name'])
    op.drop_constraint(op.f('files_folder_id_fkey'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_uploader_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'folders', ['folder_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'files', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('files', 'uploader_id')
    op.drop_column('files', 'filename')
    op.drop_column('files', 'filepath')
    # op.alter_column('folders', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            nullable=True,
    #            existing_server_default=sa.text('now()'))
    # op.alter_column('folders', 'updated_at',
    #            existing_type=postgresql.TIMESTAMP(),
    #            nullable=True,
    #            existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('folders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('folders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('files', sa.Column('filepath', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('uploader_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_uploader_id_fkey'), 'files', 'users', ['uploader_id'], ['id'])
    op.create_foreign_key(op.f('files_folder_id_fkey'), 'files', 'folders', ['folder_id'], ['id'])
    op.drop_constraint(None, 'files', type_='unique')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.alter_column('files', 'folder_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('files', 'updated_at')
    op.drop_column('files', 'created_at')
    op.drop_column('files', 'owner_id')
    op.drop_column('files', 'file_size')
    op.drop_column('files', 'mime_type')
    op.drop_column('files', 'file_path')
    op.drop_column('files', 'stored_name')
    op.drop_column('files', 'original_name')
    # ### end Alembic commands ###
