"""add soft delete to files

Revision ID: bc6517fc6c49
Revises: 8006b116573c
Create Date: 2026-07-27 01:31:35.341280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc6517fc6c49'
down_revision: Union[str, Sequence[str], None] = '8006b116573c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        "files",
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.add_column(
        "files",
        sa.Column(
            "deleted_at",
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.alter_column(
        "files",
        "is_deleted",
        server_default=None,
    )
# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('files', sa.Column('is_deleted', sa.Boolean(), nullable=False,server_default=sa.false()))
#     op.add_column('files', sa.Column('deleted_at', sa.DateTime(), nullable=True))
#     op.alter_column('folders', 'created_at',
#                existing_type=postgresql.TIMESTAMP(),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('folders', 'updated_at',
#                existing_type=postgresql.TIMESTAMP(),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('folders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('folders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('files', 'deleted_at')
    op.drop_column('files', 'is_deleted')
    # ### end Alembic commands ###
